version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

# from https://github.com/jwilder/nginx-proxy/issues/502
# I also have to put this at the bottom of all other dev docker-compose files.
# I ran this as well, needs to be run once per docker SERVER: docker network create nginx-proxy
#     This is needed so nginx-proxy can be used across compose files.
networks:
  default:
    external:
      name: nginx-proxy

